-- Ranchão Bebidas — módulo Manutenção
-- Execute uma única vez no SQL Editor do Supabase.

create table if not exists public.manutencoes (
  id bigint generated by default as identity primary key,
  loja text not null check (loja in ('loja1','loja2')),
  tipo text not null check (tipo in ('computador','loja','veiculo')),
  data_manutencao date not null,
  item text not null,
  descricao text not null,
  fornecedor text,
  valor numeric(14,2) not null default 0 check (valor >= 0),
  status text not null default 'realizada' check (status in ('realizada','agendada','em_andamento','cancelada')),
  proxima_data date,
  observacoes text,
  arquivo_nome text,
  arquivo_tipo text,
  caminho_storage text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

-- Atualiza instalações que já possuíam a primeira versão do módulo.
alter table public.manutencoes
  add column if not exists arquivo_nome text,
  add column if not exists arquivo_tipo text,
  add column if not exists caminho_storage text;

create index if not exists manutencoes_loja_tipo_data_idx
  on public.manutencoes (loja, tipo, data_manutencao desc);

create or replace function public.atualizar_data_manutencoes()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.atualizado_em = now();
  return new;
end;
$$;

drop trigger if exists trg_atualizar_data_manutencoes on public.manutencoes;
create trigger trg_atualizar_data_manutencoes
before update on public.manutencoes
for each row execute function public.atualizar_data_manutencoes();

alter table public.manutencoes enable row level security;
alter table public.manutencoes force row level security;

revoke all on table public.manutencoes from anon;
grant select, insert, update, delete on table public.manutencoes to authenticated;
grant usage, select on sequence public.manutencoes_id_seq to authenticated;

drop policy if exists "manutencoes_usuario_autenticado" on public.manutencoes;
create policy "manutencoes_usuario_autenticado"
on public.manutencoes
for all
to authenticated
using (auth.uid() is not null)
with check (auth.uid() is not null);

-- Bucket privado para fotos e PDFs das manutenções.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'manutencoes',
  'manutencoes',
  false,
  15728640,
  array['application/pdf','image/jpeg','image/png','image/webp','image/gif','image/heic','image/heif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "manutencoes_arquivos_select" on storage.objects;
create policy "manutencoes_arquivos_select"
on storage.objects for select to authenticated
using (bucket_id = 'manutencoes' and auth.uid() is not null);

drop policy if exists "manutencoes_arquivos_insert" on storage.objects;
create policy "manutencoes_arquivos_insert"
on storage.objects for insert to authenticated
with check (bucket_id = 'manutencoes' and auth.uid() is not null);

drop policy if exists "manutencoes_arquivos_delete" on storage.objects;
create policy "manutencoes_arquivos_delete"
on storage.objects for delete to authenticated
using (bucket_id = 'manutencoes' and auth.uid() is not null);

notify pgrst, 'reload schema';
