-- Ranchão Bebidas — módulo Controle de Estoque
-- Execute este arquivo uma única vez no SQL Editor do Supabase.

create table if not exists public.controle_estoque_mensal (
  id bigint generated by default as identity primary key,
  loja text not null check (loja in ('loja1', 'loja2')),
  mes text not null check (mes ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  estoque_inicial_manual numeric(14,2) check (estoque_inicial_manual is null or estoque_inicial_manual >= 0),
  compras_manual numeric(14,2) check (compras_manual is null or compras_manual >= 0),
  bonificacoes_manual numeric(14,2) check (bonificacoes_manual is null or bonificacoes_manual >= 0),
  estoque_final_manual numeric(14,2) check (estoque_final_manual is null or estoque_final_manual >= 0),
  cmv_manual numeric(14,2) check (cmv_manual is null or cmv_manual >= 0),
  receita_manual numeric(14,2) check (receita_manual is null or receita_manual >= 0),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  constraint controle_estoque_mensal_loja_mes_key unique (loja, mes)
);

alter table public.controle_estoque_mensal enable row level security;
alter table public.controle_estoque_mensal force row level security;

revoke all on table public.controle_estoque_mensal from anon;
grant select, insert, update, delete on table public.controle_estoque_mensal to authenticated;
grant usage, select on sequence public.controle_estoque_mensal_id_seq to authenticated;

drop policy if exists "controle_estoque_mensal_autenticado" on public.controle_estoque_mensal;
create policy "controle_estoque_mensal_autenticado"
on public.controle_estoque_mensal
for all
to authenticated
using (true)
with check (true);

create or replace function public.atualizar_data_controle_estoque()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.atualizado_em = now();
  return new;
end;
$$;

drop trigger if exists trg_controle_estoque_atualizado_em on public.controle_estoque_mensal;
create trigger trg_controle_estoque_atualizado_em
before update on public.controle_estoque_mensal
for each row execute function public.atualizar_data_controle_estoque();
