-- Ranchão Bebidas — módulo Contratos / Recibos
-- Execute uma única vez no SQL Editor do Supabase.

create table if not exists public.recibos_configuracoes (
  id bigint generated by default as identity primary key,
  loja text not null unique check (loja in ('loja1','loja2')),
  recebedor_nome text,
  recebedor_documento text,
  recebedor_endereco text,
  cidade text,
  estado text,
  pagador_nome_padrao text,
  pagador_documento_padrao text,
  pagador_endereco_padrao text,
  referencia_padrao text,
  observacao_rodape text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.recibos (
  id bigint generated by default as identity primary key,
  loja text not null check (loja in ('loja1','loja2')),
  data_recibo date not null,
  pagador_nome text not null,
  pagador_documento text,
  pagador_endereco text not null,
  valor numeric(14,2) not null check (valor > 0),
  valor_extenso text not null,
  referencia text not null,
  cidade text not null,
  estado text,
  recebedor_nome text not null,
  recebedor_documento text,
  recebedor_endereco text,
  observacao_rodape text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index if not exists recibos_loja_data_idx
  on public.recibos (loja, data_recibo desc);

alter table public.recibos_configuracoes enable row level security;
alter table public.recibos_configuracoes force row level security;
alter table public.recibos enable row level security;
alter table public.recibos force row level security;

revoke all on table public.recibos_configuracoes from anon;
revoke all on table public.recibos from anon;
grant select, insert, update, delete on table public.recibos_configuracoes to authenticated;
grant select, insert, update, delete on table public.recibos to authenticated;
grant usage, select on sequence public.recibos_configuracoes_id_seq to authenticated;
grant usage, select on sequence public.recibos_id_seq to authenticated;

drop policy if exists "recibos_configuracoes_autenticado" on public.recibos_configuracoes;
create policy "recibos_configuracoes_autenticado"
on public.recibos_configuracoes for all to authenticated
using (true) with check (true);

drop policy if exists "recibos_autenticado" on public.recibos;
create policy "recibos_autenticado"
on public.recibos for all to authenticated
using (true) with check (true);

create or replace function public.atualizar_data_recibos()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.atualizado_em = now();
  return new;
end;
$$;

drop trigger if exists trg_recibos_configuracoes_atualizado_em on public.recibos_configuracoes;
create trigger trg_recibos_configuracoes_atualizado_em
before update on public.recibos_configuracoes
for each row execute function public.atualizar_data_recibos();

drop trigger if exists trg_recibos_atualizado_em on public.recibos;
create trigger trg_recibos_atualizado_em
before update on public.recibos
for each row execute function public.atualizar_data_recibos();
