-- Ranchão Bebidas — módulo de contracheques para controle interno
-- Execute este arquivo uma única vez no SQL Editor do Supabase.

alter table public.recibos_configuracoes
  add column if not exists empresa_razao_social text,
  add column if not exists empresa_nome_fantasia text,
  add column if not exists empresa_cnpj text,
  add column if not exists empresa_endereco text;

create table if not exists public.contracheques (
  id bigint generated by default as identity primary key,
  loja text not null check (loja in ('loja1','loja2')),
  competencia text not null check (competencia ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'),
  data_pagamento date not null,
  funcionario_nome text not null,
  funcionario_cpf text not null,
  cargo text not null,
  data_admissao date,
  salario_base numeric(14,2) not null check (salario_base >= 0),
  proventos jsonb not null default '[]'::jsonb,
  descontos jsonb not null default '[]'::jsonb,
  total_proventos numeric(14,2) not null check (total_proventos >= 0),
  total_descontos numeric(14,2) not null check (total_descontos >= 0),
  valor_liquido numeric(14,2) not null check (valor_liquido >= 0),
  empresa_razao_social text,
  empresa_nome_fantasia text,
  empresa_cnpj text,
  empresa_endereco text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index if not exists contracheques_loja_competencia_idx
  on public.contracheques (loja, competencia desc);

create or replace function public.atualizar_data_contracheques()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.atualizado_em = now();
  return new;
end;
$$;

drop trigger if exists trg_atualizar_data_contracheques on public.contracheques;
create trigger trg_atualizar_data_contracheques
before update on public.contracheques
for each row execute function public.atualizar_data_contracheques();

alter table public.contracheques enable row level security;
alter table public.contracheques force row level security;

revoke all on table public.contracheques from anon;
grant select, insert, update, delete on table public.contracheques to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "contracheques_usuario_autenticado" on public.contracheques;
create policy "contracheques_usuario_autenticado"
on public.contracheques
for all
to authenticated
using (auth.uid() is not null)
with check (auth.uid() is not null);
