-- Ranchão Bebidas - módulo Dúvidas
-- Execute uma única vez em: Supabase > SQL Editor > New query > Run.

begin;

create table if not exists public.duvidas (
  id bigint generated by default as identity primary key,
  loja text not null check (loja in ('loja1','loja2','geral')),
  titulo text not null check (char_length(titulo) between 1 and 180),
  categoria text not null check (char_length(categoria) between 1 and 80),
  conteudo text not null check (char_length(conteudo) between 1 and 10000),
  palavras_chave text check (palavras_chave is null or char_length(palavras_chave) <= 300),
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create index if not exists duvidas_loja_atualizado_idx
  on public.duvidas (loja, atualizado_em desc);

-- Atualização para tornar o módulo geral, sem seletor de loja.
alter table public.duvidas drop constraint if exists duvidas_loja_check;
alter table public.duvidas
  add constraint duvidas_loja_check check (loja in ('loja1','loja2','geral'));

-- Preserva informações já cadastradas em testes e passa tudo para a área geral.
update public.duvidas set loja = 'geral' where loja in ('loja1','loja2');

alter table public.duvidas enable row level security;
alter table public.duvidas force row level security;

revoke all privileges on table public.duvidas from anon;
grant select, insert, update, delete on table public.duvidas to authenticated;
grant usage, select on sequence public.duvidas_id_seq to authenticated;
revoke all privileges on sequence public.duvidas_id_seq from anon;

drop policy if exists erp_authenticated_access on public.duvidas;
create policy erp_authenticated_access
on public.duvidas
for all
to authenticated
using ((select auth.uid()) is not null)
with check ((select auth.uid()) is not null);

commit;

-- Conferência: o resultado deve mostrar rls_ativo = true.
select schemaname, tablename, rowsecurity as rls_ativo
from pg_tables
where schemaname = 'public' and tablename = 'duvidas';
