-- Ranchão Bebidas — módulo Vendas > Orçamentos
-- Execute uma única vez no SQL Editor do Supabase.

create table if not exists public.orcamentos (
  id bigint generated by default as identity primary key,
  loja text not null check (loja in ('loja1','loja2')),
  data_emissao date not null,
  data_validade date not null,
  cliente_nome text not null,
  cliente_telefone text,
  cliente_documento text,
  forma_pagamento text,
  observacoes text,
  status text not null default 'aberto' check (status in ('aberto','aprovado','recusado','vencido')),
  itens jsonb not null default '[]'::jsonb,
  subtotal numeric(14,2) not null default 0 check (subtotal >= 0),
  desconto numeric(14,2) not null default 0 check (desconto >= 0),
  valor_entrega numeric(14,2) not null default 0 check (valor_entrega >= 0),
  total numeric(14,2) not null default 0 check (total >= 0),
  empresa_razao_social text,
  empresa_nome_fantasia text,
  empresa_cnpj text,
  empresa_endereco text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  check (data_validade >= data_emissao),
  check (jsonb_typeof(itens) = 'array')
);

create index if not exists orcamentos_loja_data_idx
  on public.orcamentos (loja, data_emissao desc);

create index if not exists orcamentos_loja_status_idx
  on public.orcamentos (loja, status);

create or replace function public.atualizar_data_orcamentos()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.atualizado_em = now();
  return new;
end;
$$;

drop trigger if exists trg_atualizar_data_orcamentos on public.orcamentos;
create trigger trg_atualizar_data_orcamentos
before update on public.orcamentos
for each row execute function public.atualizar_data_orcamentos();

alter table public.orcamentos enable row level security;
alter table public.orcamentos force row level security;

revoke all on table public.orcamentos from anon;
grant select, insert, update, delete on table public.orcamentos to authenticated;
grant usage, select on all sequences in schema public to authenticated;

drop policy if exists "orcamentos_usuario_autenticado" on public.orcamentos;
create policy "orcamentos_usuario_autenticado"
on public.orcamentos
for all
to authenticated
using (auth.uid() is not null)
with check (auth.uid() is not null);
