-- Ranchão Bebidas — Etapa 2: histórico de alterações
-- Execute todo este arquivo uma única vez no SQL Editor do Supabase.

create table if not exists public.historico_alteracoes (
  id bigint generated by default as identity primary key,
  criado_em timestamptz not null default now(),
  usuario_id uuid null,
  usuario_email text null,
  acao text not null check (acao in ('inseriu','alterou','excluiu')),
  tabela text not null,
  registro_id text null,
  loja text null,
  dados_anteriores jsonb null,
  dados_novos jsonb null,
  campos_alterados text[] not null default '{}'::text[]
);

create index if not exists historico_alteracoes_criado_em_idx
  on public.historico_alteracoes (criado_em desc);
create index if not exists historico_alteracoes_loja_criado_em_idx
  on public.historico_alteracoes (loja, criado_em desc);
create index if not exists historico_alteracoes_tabela_criado_em_idx
  on public.historico_alteracoes (tabela, criado_em desc);

alter table public.historico_alteracoes enable row level security;

drop policy if exists "historico_select_authenticated" on public.historico_alteracoes;
create policy "historico_select_authenticated"
  on public.historico_alteracoes
  for select
  to authenticated
  using (true);

revoke insert, update, delete on public.historico_alteracoes from anon, authenticated;
grant select on public.historico_alteracoes to authenticated;

create or replace function public.registrar_historico_alteracao()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_antes jsonb;
  v_depois jsonb;
  v_acao text;
  v_registro_id text;
  v_loja text;
  v_campos text[] := '{}'::text[];
begin
  if tg_op = 'INSERT' then
    v_acao := 'inseriu';
    v_depois := to_jsonb(new);
  elsif tg_op = 'UPDATE' then
    v_antes := to_jsonb(old);
    v_depois := to_jsonb(new);
    if v_antes = v_depois then
      return new;
    end if;
    v_acao := 'alterou';
    select coalesce(array_agg(chave order by chave), '{}'::text[])
      into v_campos
      from (
        select chave
        from jsonb_object_keys(v_antes || v_depois) as chaves(chave)
        where v_antes -> chave is distinct from v_depois -> chave
      ) alterados;
  else
    v_acao := 'excluiu';
    v_antes := to_jsonb(old);
  end if;

  v_registro_id := coalesce(
    v_depois ->> 'id', v_antes ->> 'id',
    v_depois ->> 'chave', v_antes ->> 'chave',
    v_depois ->> 'uuid', v_antes ->> 'uuid'
  );
  v_loja := coalesce(v_depois ->> 'loja', v_antes ->> 'loja');

  insert into public.historico_alteracoes (
    usuario_id, usuario_email, acao, tabela, registro_id, loja,
    dados_anteriores, dados_novos, campos_alterados
  ) values (
    auth.uid(),
    coalesce(auth.jwt() ->> 'email', current_setting('request.jwt.claim.email', true), current_user),
    v_acao, tg_table_name, v_registro_id, v_loja,
    v_antes, v_depois, v_campos
  );

  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

do $$
declare
  nome_tabela text;
  tabelas text[] := array[
    'configuracoes','recibos_configuracoes','bh_funcionarios','bh_registros','bh_atestados',
    'lancamentos','comprovantes','fluxo_caixa_contas','fluxo_caixa_saldos','fluxo_caixa_lancamentos',
    'caixa_diferencas','checklist_itens','checklist_execucoes','compras_empresas','compras_marcas',
    'fornecedores','compras_produtos','controle_estoque_mensal','estoque_inventarios','contagens_estoque',
    'contagens_estoque_itens','comb_pag_compras','comb_pag_pagamentos','pagamentos_caixa',
    'pagamentos_caixa_memoria','pagamentos_caixa_tipos','vendas_delivery','vendas_itens','orcamentos',
    'recibos','contracheques','duvidas','manutencoes','leituras_comprovantes','despesas_fixas',
    'despesas_fixas_puladas'
  ];
begin
  foreach nome_tabela in array tabelas loop
    if to_regclass('public.' || nome_tabela) is not null then
      execute format('drop trigger if exists trg_historico_alteracoes on public.%I', nome_tabela);
      execute format(
        'create trigger trg_historico_alteracoes after insert or update or delete on public.%I for each row execute function public.registrar_historico_alteracao()',
        nome_tabela
      );
    end if;
  end loop;
end;
$$;

comment on table public.historico_alteracoes is
  'Registro automático de inclusões, alterações e exclusões realizadas no sistema Ranchão Bebidas.';
