-- Ranchão Bebidas - módulo Leitura de Comprovantes
-- Execute uma única vez no SQL Editor do Supabase.

begin;

create table if not exists public.leituras_comprovantes (
  id bigint generated by default as identity primary key,
  loja text not null check (loja in ('loja1','loja2')),
  numero integer,
  recebedor text not null,
  documento text,
  valor numeric(14,2) not null check (valor > 0),
  data_pagamento date not null,
  horario_pagamento time,
  modelo text,
  codigo_transacao text,
  arquivo_hash text not null,
  nome_arquivo text not null,
  caminho_storage text not null,
  tipo_arquivo text not null default 'application/pdf',
  tamanho_bytes bigint,
  criado_em timestamptz not null default now()
);

create index if not exists leituras_comprovantes_loja_data_idx
  on public.leituras_comprovantes (loja, data_pagamento desc);

create unique index if not exists leituras_comprovantes_hash_unico
  on public.leituras_comprovantes (loja, arquivo_hash);

create unique index if not exists leituras_comprovantes_transacao_unica
  on public.leituras_comprovantes (loja, codigo_transacao)
  where codigo_transacao is not null and codigo_transacao <> '';

alter table public.leituras_comprovantes enable row level security;
alter table public.leituras_comprovantes force row level security;

revoke all on table public.leituras_comprovantes from anon;
grant select, insert, update, delete on table public.leituras_comprovantes to authenticated;
grant usage, select on sequence public.leituras_comprovantes_id_seq to authenticated;

drop policy if exists leituras_comprovantes_autenticado on public.leituras_comprovantes;
create policy leituras_comprovantes_autenticado
on public.leituras_comprovantes
for all to authenticated
using ((select auth.uid()) is not null)
with check ((select auth.uid()) is not null);

-- Reaproveita o bucket privado já utilizado pelos comprovantes do Financeiro.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'comprovantes',
  'comprovantes',
  false,
  15728640,
  array['image/jpeg','image/png','image/webp','application/pdf']
)
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists leitura_comprovantes_storage_select on storage.objects;
create policy leitura_comprovantes_storage_select
on storage.objects for select to authenticated
using (bucket_id = 'comprovantes' and (select auth.uid()) is not null);

drop policy if exists leitura_comprovantes_storage_insert on storage.objects;
create policy leitura_comprovantes_storage_insert
on storage.objects for insert to authenticated
with check (bucket_id = 'comprovantes' and (select auth.uid()) is not null);

drop policy if exists leitura_comprovantes_storage_delete on storage.objects;
create policy leitura_comprovantes_storage_delete
on storage.objects for delete to authenticated
using (bucket_id = 'comprovantes' and (select auth.uid()) is not null);

commit;

notify pgrst, 'reload schema';

select schemaname, tablename, rowsecurity as rls_ativo
from pg_tables
where schemaname='public' and tablename='leituras_comprovantes';
